/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORT1_8 (coord A1), P1_8/J9[32]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_RX_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_RX_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_RX_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                                        /* @} */

/*! @name PORT1_9 (coord B1), P1_9/J9[30]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_TX_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_TX_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_TX_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UARTPins(void);

/*! @name PORT0_1 (coord A16), P0_1/SWCLK/J23[4]/D16[5]/J22[2]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDCLK_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDCLK_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDCLK_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                                          /* @} */

/*! @name PORT0_0 (coord A17), P0_0/SWDIO/J23[2]/D16[6]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDIO_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDIO_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDIO_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                                         /* @} */

/*! @name PORT0_2 (coord B16), P0_2/SWO/J23[6]/D16[4]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWO_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWO_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWO_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSWD_DEBUGPins(void);

/*! @name PORT1_2 (coord C4), P1_2/SJ4[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_LED_BLUE_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_BLUE_GPIO_PIN 2U              /*!<@brief GPIO pin number */
#define BOARD_INITLEDSPINS_LED_BLUE_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDSPINS_LED_BLUE_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_BLUE_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_LED_BLUE_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT0_27 (coord E10), P0_27/SJ6[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_LED_GREEN_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_GREEN_GPIO_PIN 27U              /*!<@brief GPIO pin number */
#define BOARD_INITLEDSPINS_LED_GREEN_GPIO_PIN_MASK (1U << 27U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDSPINS_LED_GREEN_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_GREEN_PIN 27U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_LED_GREEN_PIN_MASK (1U << 27U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLEDsPins(void);

/*! @name PORT0_6 (coord C14), P0_6/J23[7]/SW3[3]/SW3[4]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBUTTONSPINS_SW3_GPIO GPIO0               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW3_GPIO_PIN 6U              /*!<@brief GPIO pin number */
#define BOARD_INITBUTTONSPINS_SW3_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITBUTTONSPINS_SW3_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW3_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITBUTTONSPINS_SW3_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT0_23 (coord B7), P0_23/SJ9[1]/SW2[3]/SW2[4]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBUTTONSPINS_SW2_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW2_GPIO_PIN 23U              /*!<@brief GPIO pin number */
#define BOARD_INITBUTTONSPINS_SW2_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITBUTTONSPINS_SW2_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW2_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITBUTTONSPINS_SW2_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitBUTTONsPins(void);

#define PCR_DSE_dse0 0x00u /*!<@brief Drive Strength Enable: Low */
#define PCR_DSE_dse1 0x01u /*!<@brief Drive Strength Enable: High */
#define PCR_IBE_ibe1 0x01u /*!<@brief Input Buffer Enable: Enables */

/*! @name PORT0_2 (coord B16), P0_2/SWO/J23[6]/D16[4]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DEBUG_SWD_SWO_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_SWD_SWO_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_SWD_SWO_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name ADC0_A0 (coord P3), ADC0_A0/ARD_A0/J4[2]/Potentiometer/ADC0_A0/ARD_A0/J4[2]/ADC0_A0/ARD_A0/J4[2]
  @{ */
/* @} */

/*! @name PORT4_12 (coord T6), P4_12/SJ25[1]/J8[17]/Switch_0/P4_12/SJ25[1]/J8[17]/P4_12/SJ25[1]/J8[17]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Switch_0_GPIO GPIO4                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Switch_0_GPIO_PIN 12U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_Switch_0_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Switch_0_PORT PORT4                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Switch_0_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Switch_0_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT0_14 (coord E11), P0_14/J4[6]/SJ19[3]/Switch_1/P0_14/J4[6]/SJ19[3]/P0_14/J4[6]/SJ19[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Switch_1_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Switch_1_GPIO_PIN 14U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_Switch_1_GPIO_PIN_MASK (1U << 14U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Switch_1_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Switch_1_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Switch_1_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT0_22 (coord B8), P0_22/J4[8]/SJ18[3]/Switch_2/P0_22/J4[8]/SJ18[3]/P0_22/J4[8]/SJ18[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Switch_2_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Switch_2_GPIO_PIN 22U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_Switch_2_GPIO_PIN_MASK (1U << 22U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Switch_2_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Switch_2_PIN 22U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Switch_2_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT0_30 (coord E7), P0_30/SJ2[1]/LED_0/P0_30/SJ2[1]/P0_30/SJ2[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_0_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_0_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LED_0_GPIO_PIN 30U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LED_0_GPIO_PIN_MASK (1U << 30U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_0_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_0_PIN 30U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_0_PIN_MASK (1U << 30U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORT4_16 (coord R8), P4_16/SJ23[1]/J8[21]/LED_1/P4_16/SJ23[1]/J8[21]/P4_16/SJ23[1]/J8[21]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_1_GPIO GPIO4                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_1_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LED_1_GPIO_PIN 16U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LED_1_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_1_PORT PORT4                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_1_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_1_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORT1_23 (coord M4), P1_23/J9[23]/SJ1[1]/LED_2/P1_23/J9[23]/SJ1[1]/P1_23/J9[23]/SJ1[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_2_GPIO GPIO1                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_2_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LED_2_GPIO_PIN 23U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_LED_2_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_2_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_2_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_2_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORT4_20 (coord T10), P4_20/SJ21[1]/J8[25]/Button_0/P4_20/SJ21[1]/J8[25]/P4_20/SJ21[1]/J8[25]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Button_0_GPIO GPIO4                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Button_0_GPIO_PIN 20U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_Button_0_GPIO_PIN_MASK (1U << 20U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Button_0_PORT PORT4                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Button_0_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Button_0_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT0_15 (coord G13), P0_15/SJ8[1]/Button_1/P0_15/SJ8[1]/P0_15/SJ8[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Button_1_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Button_1_GPIO_PIN 15U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_Button_1_GPIO_PIN_MASK (1U << 15U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Button_1_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Button_1_PIN 15U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Button_1_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT2_4 (coord K3), P2_4/TP26/J12[5]/J3[11]/SJ5[3]/RGB_A1_PWM/P2_4/TP26/J12[5]/J3[11]/SJ5[3]/P2_4/TP26/J12[5]/J3[11]/SJ5[3]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RGB_A1_PWM_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RGB_A1_PWM_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RGB_A1_PWM_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT2_5 (coord K1), P2_5/TP25/J12[3]/J3[9]/SJ6[3]/RGB_B1_PWM/P2_5/TP25/J12[3]/J3[9]/SJ6[3]/P2_5/TP25/J12[3]/J3[9]/SJ6[3]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RGB_B1_PWM_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RGB_B1_PWM_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RGB_B1_PWM_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT2_2 (coord H3), P2_2/TP5/J12[8]/J3[7]/SJ7[3]/RGB_A2_PWM/P2_2/TP5/J12[8]/J3[7]/SJ7[3]/P2_2/TP5/J12[8]/J3[7]/SJ7[3]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_RGB_A2_PWM_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_RGB_A2_PWM_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_RGB_A2_PWM_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT0_24 (coord B6), P0_24/SJ7[1]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_PWMA_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_PWMA_PIN 24U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PWMA_PIN_MASK (1U << 24U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORT2_6 (coord K2), P2_6/TP24/J12[2]/J3[15]/SJ1[3]/RGB_A0_PWM/P2_6/TP24/J12[2]/J3[15]/SJ1[3]/P2_6/TP24/J12[2]/J3[15]/SJ1[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Motor_AIN1_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Motor_AIN1_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_Motor_AIN1_GPIO_PIN 6U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_Motor_AIN1_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Motor_AIN1_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Motor_AIN1_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Motor_AIN1_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT2_7 (coord L2), P2_7/TP23/J12[1]/J3[13]/SJ3[3]/RGB_B0_PWM/P2_7/TP23/J12[1]/J3[13]/SJ3[3]/P2_7/TP23/J12[1]/J3[13]/SJ3[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Motor_AIN2_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Motor_AIN2_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_Motor_AIN2_GPIO_PIN 7U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_Motor_AIN2_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Motor_AIN2_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Motor_AIN2_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Motor_AIN2_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT2_0 (coord H2), P2_0/J3[1]/SJ8[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Motor_STANDBY_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Motor_STANDBY_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_Motor_STANDBY_GPIO_PIN 0U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_Motor_STANDBY_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Motor_STANDBY_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Motor_STANDBY_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Motor_STANDBY_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT0_26 (coord F10), P0_26/J2[10]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_PWMB_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_PWMB_PIN 26U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_PWMB_PIN_MASK (1U << 26U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PORT2_3 (coord J3), P2_3/TP4/J12[7]/J3[5]/SJ4[3]/RGB_B2_PWM/P2_3/TP4/J12[7]/J3[5]/SJ4[3]/P2_3/TP4/J12[7]/J3[5]/SJ4[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Motor_BIN1_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Motor_BIN1_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_Motor_BIN1_GPIO_PIN 3U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_Motor_BIN1_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Motor_BIN1_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Motor_BIN1_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Motor_BIN1_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT1_22 (coord L4), P1_22/J9[24]/J3[3]/SJ9[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Motor_BIN2_GPIO GPIO1                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Motor_BIN2_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_Motor_BIN2_GPIO_PIN 22U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_Motor_BIN2_GPIO_PIN_MASK (1U << 22U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Motor_BIN2_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Motor_BIN2_PIN 22U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Motor_BIN2_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT4_18 (coord N10), P4_18/J8[23]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Board_output_PORT PORT4                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Board_output_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Board_output_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT4_22 (coord T12), P4_22/J8[27]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_Board_input_PORT PORT4                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Board_input_PIN 22U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Board_input_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT4_1 (coord P2), P4_1/J8[3]/SJ15[1]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_OLED_I2C_SCK_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_OLED_I2C_SCK_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_OLED_I2C_SCK_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT4_0 (coord P1), P4_0/J8[4]/SJ14[1]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_OLED_I2C_SDA_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_OLED_I2C_SDA_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_OLED_I2C_SDA_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT3_23 (coord M15), P3_23/J6[3]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_microSD_CS_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_microSD_CS_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_microSD_CS_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT3_21 (coord L16), P3_21/J6[4]/J1[15]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_microSD_CLK_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_microSD_CLK_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_microSD_CLK_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT3_22 (coord M16), P3_22/J6[5]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_microSD_MISO_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_microSD_MISO_PIN 22U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_microSD_MISO_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT3_20 (coord M17), P3_20/J6[6]/J1[5]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_microSD_MOSI_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_microSD_MOSI_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_microSD_MOSI_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins1(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitI3CPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
