/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v15.0
processor: MCXN947
package_id: MCXN947VDF
mcu_data: ksdk2_0
processor_version: 25.06.10
board: FRDM-MCXN947
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: f3b6730c-700a-42af-b404-135d56fee875
  called_from_default_init: true
  selectedCore: cm33_core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
  - global_init: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gpio_adapter_common'
- type_id: 'gpio_adapter_common'
- global_gpio_adapter_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common'
- global_USART_CMSIS_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table: []
    - interrupts: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_init(void) {
} */

/***********************************************************************************************************************
 * I3C1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'I3C1'
- type: 'i3c'
- mode: 'polling'
- custom_name_enabled: 'false'
- type_id: 'i3c_2.12.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'I3C1'
- config_sets:
  - fsl_i3c:
    - i3c_mode: 'master'
    - clock_config_master:
      - clockSource: 'FunctionClock'
      - clockSourceFreq: 'custom:4 Mhz'
    - clock_config_slave:
      - clockSource: 'SlowClock'
      - clockSourceFreq: 'custom:1000000'
    - master_config:
      - enableMaster: 'kI3C_MasterOn'
      - disableTimeout: 'false'
      - hKeep: 'kI3C_MasterHighKeeperNone'
      - enableOpenDrainStop: 'true'
      - enableOpenDrainHigh: 'true'
      - baudRate_Hz:
        - i3cPushPullBaud: '12500000'
        - i3cOpenDrainBaud: '2500000'
        - i2cBaud: '400000'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const i3c_master_config_t I3C1_master_config = {
  .enableMaster = kI3C_MasterOn,
  .disableTimeout = false,
  .hKeep = kI3C_MasterHighKeeperNone,
  .enableOpenDrainStop = true,
  .enableOpenDrainHigh = true,
  .baudRate_Hz = {
    .i3cPushPullBaud = 12500000UL,
    .i3cOpenDrainBaud = 2500000UL,
    .i2cBaud = 400000UL
  },
  .slowClock_Hz = I3C1_SLOW_CLOCK_SOURCE,
};

static void I3C1_init(void) {
  /* Initialization function */
  I3C_MasterInit(I3C1_PERIPHERAL, &I3C1_master_config, I3C1_CLOCK_SOURCE_MASTER);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Initialize components */
  I3C1_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
