/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_lpadc.h"
#include "fsl_pwm.h"
#include "fsl_spc.h"
#include "fsl_vref.h"
#include "fsl_ctimer.h"
#include "fsl_clock.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Alias for ADC1 peripheral */
#define ADC1_PERIPHERAL ADC1
/* Definition of peripheral ID */
#define PWM0_PERIPHERAL PWM0
/* Definition of submodule 0 ID */
#define PWM0_SM0 kPWM_Module_0
/* Definition of clock source of submodule 0 frequency in Hertz */
#define PWM0_SM0_SM_CLK_SOURCE_FREQ_HZ 150000000U
/* Definition of submodule 0 counter clock source frequency in Hertz - PWM0_SM0_SM_CLK_SOURCE_FREQ_HZ divided by prescaler */
#define PWM0_SM0_COUNTER_CLK_SOURCE_FREQ_HZ 150000000U
/* Definition of submodule 0 counter (PWM) frequency in Hertz */
#define PWM0_SM0_COUNTER_FREQ_HZ 20000U
/* Definition of submodule 0 channel A ID */
#define PWM0_SM0_A kPWM_PwmA
/* Definition of submodule 0 channel B ID */
#define PWM0_SM0_B kPWM_PwmB
/* Definition of submodule 0 channel X ID */
#define PWM0_SM0_X kPWM_PwmX
/* Definition of fault Fault0 ID */
#define PWM0_F0_FAULT0 kPWM_Fault_0
/* Definition of fault Fault1 ID */
#define PWM0_F0_FAULT1 kPWM_Fault_1
/* Definition of fault Fault2 ID */
#define PWM0_F0_FAULT2 kPWM_Fault_2
/* Definition of fault Fault3 ID */
#define PWM0_F0_FAULT3 kPWM_Fault_3
/* Definition of peripheral ID */
#define VREF0_PERIPHERAL VREF0
/* Definition of peripheral ID */
#define CTIMER0_PERIPHERAL CTIMER0
/* Timer tick frequency in Hz (input frequency of the timer) */
#define CTIMER0_TICK_FREQ 150000000UL
/* Timer tick period in ns (input period of the timer) */
#define CTIMER0_TICK_PERIOD 7UL
/* Definition of PWM period channel. */
#define CTIMER0_PWM_PERIOD_CH kCTIMER_Match_0
/* Definition of PWM period */
#define CTIMER0_PWM_PERIOD 7499

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const lpadc_config_t ADC1_config;
extern pwm_config_t PWM0_SM0_config;

extern const pwm_fault_input_filter_param_t PWM0_faultInputFilter_config;
extern const pwm_fault_param_t PWM0_Fault0_fault_config;
extern const pwm_fault_param_t PWM0_Fault1_fault_config;
extern const pwm_fault_param_t PWM0_Fault2_fault_config;
extern const pwm_fault_param_t PWM0_Fault3_fault_config;
extern const ctimer_config_t CTIMER0_config;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
